# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ============================================
  # FRONTEND TESTS
  # ============================================
  frontend-test:
    runs-on: ubuntu-latest
    name: Frontend - Test & Build

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        working-directory: Lu1KeuzeKompas
        run: npm ci
        
      - name: Install Playwright browsers
        working-directory: Lu1KeuzeKompas
        run: npx playwright install --with-deps

      - name: Build Angular
        working-directory: Lu1KeuzeKompas
        run: npm run build

      - name: Run E2E tests
        working-directory: Lu1KeuzeKompas
        run: npm run e2e -- --project=chromium

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: Lu1KeuzeKompas/playwright-report/

  # ============================================
  # BACKEND TESTS
  # ============================================
  backend-test:
    runs-on: ubuntu-latest
    name: Backend - Test & Build

    services:
      mongodb:
        image: mongo:latest
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          nnode-version: '22.19.0'

      - name: Install dependencies
        working-directory: backend-lu1-mongodb
        run: npm ci

      - name: Build NestJS
        working-directory: backend-lu1-mongodb
        run: npm run build

      - name: Run tests
        working-directory: backend-lu1-mongodb
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/test

  # ============================================
  # FRONTEND DEPLOY (GitHub Pages)
  # ============================================
  frontend-deploy:
    runs-on: ubuntu-latest
    name: Frontend - Deploy to GitHub Pages
    needs: frontend-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        working-directory: Lu1KeuzeKompas
        run: npm ci

      - name: Build for production
        working-directory: Lu1KeuzeKompas
        run: ng build --configuration production --base-href "/Full-Stack-LU1-opdracht2/"

      - name: Deploy to GitHub Pages
        run: |
          cd Lu1KeuzeKompas
          npm install -D gh-pages
          npx gh-pages -d dist/lu1-keuzekompas/browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}